config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'welcome#home'
  get 'welcome/:user_name', to: 'welcome#name'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name, presence: true
  validates :zip_code,
    presence: true,
    uniqueness: true,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_table_gossip_tags

  validates :title,
    presence: true,
    length: { minimum: 3, maximum: 14 }
  validates :content, presence: true
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: "recipient_id", class_name: "PrivateMessage"

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :password,
    presence: true,
    length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
    @user_city = City.all.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
  end

  def show
    @my_gossip = Gossip.all.find(params[:id])
  end

  def new
  end

  def create
    new_gossip = Gossip.new
    new_gossip.id = Gossip.all.last.id + 1
    new_gossip.title = params[:gossip_title]
    new_gossip.content = params[:gossip_content]
    new_gossip.user = current_user
    if new_gossip.save
      redirect_to "/"
    else
      render "/gossips/new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:user_email])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if user && user.authenticate(params[:user_password])
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas
      redirect_to '/'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def team
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
    if params[:new_password] == params[:new_password_confirmation]
      u = User.new
      u.id = User.all.length + 1
      u.email = params[:new_email]
      u.password = params[:new_password]
      u.first_name = params[:new_first_name]
      u.last_name = params[:new_last_name]
      u.age = params[:new_age]
      u.description = params[:new_description]
      if City.all.find_by(name: params[:new_city])
        u.city = City.all.find_by(name: params[:new_city])
      else
        c = City.new
        c.name = params[:new_city]
        c.zip_code = "#{rand(0..9)}#{rand(1..5)}#{Faker::Number.unique.between(from: 10, to: 88)}0"
        c.id = City.all.length + 1
        c.save
        u.city_id = c.id
      end
      if u.save
        puts "$" * 100
        puts "UTILISATEUR AJOUTÉ"
        redirect_to '/'
      else
        puts "$" * 100
        puts "ÇA MARCHE PAS"
        render 'new'
      end
    else
      puts "VEUILLEZ SAISIR LE MÊME MOT DE PASSE LORS DE LA CONFIRMATION"
      render 'new'
    end
  end

  def new
  end

  def edit
  end

  def show
    @my_user = User.all.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def name
    @user_first_name = params[:user_name]
    @gossip_list = Gossip.all
  end

  def home
    @gossip_list = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/model_helper.rb
module ModelHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Find me in app/views/cities/destroy.html.erb</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<h1>Ville : <%= @user_city.name %> </h1>
<br>
<h2>Voici la liste des potins écrits par les utilisateurs de cette ville :</h2>
  <% @user_city.users.each do |u| %>
    <% u.gossips.each do |g| %>
      <ul> <u><strong><%= link_to "#{g.title}", gossip_path(g.id) %></strong></u>
        <li>Potin : <%= g.content %></li>
        <li>Écrit par : <%= link_to "#{g.user.first_name}", user_path(g.user.id) %></li>
      </ul>
    <%end%> 
    <br>
  <%end%>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<h1>Gossips#edit</h1>
<p>Find me in app/views/gossips/edit.html.erb</p>

app/views/gossips/index.html.erb
<h1>Gossips#index</h1>
<p>Find me in app/views/gossips/index.html.erb</p>

app/views/gossips/new.html.erb
<h1>CRÉE TON POTIN !!!</h1>
<br><br>
<form action="/gossips" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <h3>Le titre du potin : <input type="text" name="gossip_title"></h3>
  <br>
  <h4>Le contenu du potin : <input type="text" name="gossip_content"></h4>
  <br><br>
  <input type="submit" name="valider">
</form>

app/views/gossips/show.html.erb
<h1><strong>VOICI LE POTIN N° <%= @my_gossip.id %> : </strong></h1>
<br><br>
<p><u>Titre</u> : <%= @my_gossip.title %> </p>
<br>
<p><u>Contenu</u> : <br><%= @my_gossip.content %> </p>
<br>
<p><u>Auteur</u> : <%= link_to "#{@my_gossip.user.first_name}  #{@my_gossip.user.last_name}", user_path(@my_gossip.user.id) %>, de <%= link_to "#{@my_gossip.user.city.name}", city_path(@my_gossip.user.city.id) %> </p>
<br>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>NOS E-MAILS :</h1>
<p><ul>
  <li>marine@marine.com</li>
  <li>jordy@jordy.com</li>
  <li>terence@terence.com</li>
  <li>leo@leo.com</li>
  <li>paul@paul.com</li>
  <li>max@max.com</li>
</ul></p>

app/views/static_pages/team.html.erb
<h1>VOICI LA FINE ÉQUIPE :</h1>
<p><ul>
  <li>Marine</li>
  <li>Jordy</li>
  <li>Terence</li>
  <li>Léo</li>
  <li>Paul</li>
  <li>Max</li>
</ul></p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>INSCRIS-TOI ET VIENT COMMÉRER !!!</h1>
<br><br>
<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <h3>Ton e-mail: <input type="text" name="new_email"></h3>
  <br>
  <h4>Ton mot de passe : <input type="text" name="new_password"></h4>
  <h4>Confirme ton mot de passe : <input type="text" name="new_password_confirmation"></h4>
  <br><br><br>
  <p>Prénom : <input type="text" name="new_first_name"></p>
  <p>Nom : <input type="text" name="new_last_name"></p>
  <p>Âge : <input type="text" name="new_age"></p>
  <p>Ville : <input type="text" name="new_city"></p>
  <p>Description (optionnel) : <input type="text" name="new_description"></p>
  <input type="submit" name="valider">
</form>

app/views/users/show.html.erb
<h1>Utilisateur n° <%= @my_user.id %></h1>
<br>
<p><u>Prénom :</u> <%= @my_user.first_name %></p>
<p><u>Nom :</u> <%= @my_user.last_name %></p>
<p><u>Description :</u> <%= @my_user.description %></p>
<p><u>E-Mail :</u> <%= @my_user.email %></p>
<p><u>Âge :</u> <%= @my_user.age %></p>
<p><u>Ville :</u> <%= link_to "#{@my_user.city.name}", city_path(@my_user.city.id)%></p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/home.html.erb
<% if current_user %> 

  <h1>Salut <%= current_user.first_name.titleize %> !!!</h1>
  <br>
  <h3>Clique <%= link_to "ici", new_gossip_path %> pour créer ton potin... </h3>
  <br>
  <br>
  <h2>Voici la liste des potins postés : </h2>
  <%@gossip_list.each do |g|%>
    <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
      <div class="card-header">
        <%= link_to "Potin n° #{g.id}", gossip_path(g.id) %>
      </div>
      <div class="card-body">
        <p class="card-text">
          <ul>
            <li>Titre : <%= g.title %></li>
            <br>
            <li>Auteur : <%= link_to "#{g.user.first_name}", user_path(g.user.id) %></li>
          </ul>
        </p>
      </div>
    </div>
  <%end%>

<% else %>

  <h1>Bienvenu(e) sur notre super site de commérage !!!</h1>
  <br><br>
  <h2> Inscris-toi ou connecte-toi pour venir partager de délicieux potins !!! </h2>

<% end %>

app/views/welcome/name.html.erb
<h1>Bienvenu(e) <%= @user_first_name.titleize %> !</h1>