config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'welcome#home'
  get 'welcome/:user_name', to: 'welcome#name'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name, presence: true
  validates :zip_code,
    presence: true,
    uniqueness: true,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_table_gossip_tags

  validates :title,
    presence: true,
    length: { minimum: 3, maximum: 14 }
  validates :content, presence: true
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: "recipient_id", class_name: "PrivateMessage"

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :password,
    presence: true,
    length: { minimum: 6 }

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
    @user_city = City.all.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
  end

  def show
    @my_gossip = Gossip.all.find(params[:id])
  end

  def new
  end

  def create
    new_gossip = Gossip.new
    new_gossip.id = Gossip.all.last.id + 1
    new_gossip.title = params[:gossip_title]
    new_gossip.content = params[:gossip_content]
    new_gossip.user = current_user
    if new_gossip.save
      redirect_to "/"
    else
      render "/gossips/new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:user_email])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if user && user.authenticate(params[:user_password])
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas
      redirect_to '/'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
    if params[:new_password] == params[:new_password_confirmation]
      u = User.new
      u.id = User.all.length + 1
      u.email = params[:new_email]
      u.password = params[:new_password]
      u.first_name = params[:new_first_name]
      u.last_name = params[:new_last_name]
      u.age = params[:new_age]
      u.description = params[:new_description]
      if City.all.find_by(name: params[:new_city])
        u.city = City.all.find_by(name: params[:new_city])
      else
        c = City.new
        c.name = params[:new_city]
        c.zip_code = "#{rand(0..9)}#{rand(1..5)}#{Faker::Number.unique.between(from: 10, to: 88)}0"
        c.id = City.all.length + 1
        c.save
        u.city_id = c.id
      end
      if u.save
        puts "$" * 100
        puts "UTILISATEUR AJOUTÉ"
        redirect_to '/'
      else
        puts "$" * 100
        puts "ÇA MARCHE PAS"
        render 'new'
      end
    else
      puts "VEUILLEZ SAISIR LE MÊME MOT DE PASSE LORS DE LA CONFIRMATION"
      render 'new'
    end
  end

  def new
  end

  def edit
  end

  def show
    @my_user = User.all.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def name
    @user_first_name = params[:user_name]
    @gossip_list = Gossip.all
  end

  def home
    @gossip_list = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/model_helper.rb
module ModelHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/flatly/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> 

    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      
      <a class="navbar-brand" href="/">ACCUEIL</a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item nav-link">
            <%= link_to "L'équipe", team_path %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "Nous contacter", contact_path %>
          </li>
        </ul>
      </div>

      <div>
        <% if current_user %>
          <h3 class="nav-item nav-link"> Bienvenu(e) <%= link_to "#{current_user.first_name.titleize}", user_path(current_user.id) %> ! </h3>
        <% end %>
      </div>

      <div class="dropdown">
        <% unless current_user %>
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Se connecter / S'inscrire
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to "Se connecter", new_session_path %>
            <br>
            <%= link_to "S'inscrire", new_user_path %>
          </div>
        <% else %>
          <%= link_to "Se déconnecter", session_path(session.id), method: :delete %>
        <% end %>

      </div>
    
    </nav>
    <%= yield %>
  </body>
</html>